rm -f core*
rm -f opt.out
rm -f run.pbs.*
rm -f test.*
rm -f *tec_boundary*
rm -f tacs_iter*
rm -f nan*
rm -f *.f5
rm -f *.vtk
rm -f funtofem_adjoint*
rm -f *.flow
rm -f *.grid_info
rm -f *geom_cons_law.dat
rm -f *subhist.dat
rm -f steady/Flow/core*
rm -f stead/Flow/*.vtk
rm -f steady/Flow/*tec_boundary*
rm -f steady/Flow/baseline.grid_info
rm -f steady/Flow/baseline.flow
rm -f steady/Flow/baseline_volume*
rm -f steady/Flow/baseline_hist*
rm -f steady/Flow/baseline.forces
rm -f steady/Flow/baseline.forces_imaginary
rm -f steady/Flow/*.vtk
rm -f steady/Flow/*.f5
rm -f steady/Flow/*.dat
rm -f steady/Adjoint/*
rm -f *.hst
#cp ../restart_adjoint/steady/Flow/baseline.flow steady/Flow/.
