#!/bin/bash
## Required PBS Directives --------------------------------------
#PBS -A AFVAW00262F03
#PBS -q main
#PBS -l select=8:ncpus=48:mpiprocs=48
#PBS -l walltime=16:00:00
#PBS -j oe
#PBS -N 31_ATE_KSFailure
#
## Optional Directives ------------------------------------
#PBS -M ssahu32@gatech.edu
#PBS -m be

cd $PBS_O_WORKDIR
source $HOME/.bashrc
source $HOME/.profile
#export CMPLX_MODE=1
time mpiexec_mpt -n 384 python pyopt_adjoint_heat_flux.py 2>&1 > opt.out
